version: '3.8'

services:
  app:
    image: bitrix-fastapi-image:latest  # Укажите имя и тег вашего образа FastAPI
    container_name: bitrix-fastapi
    build:
      context: .  # Укажите путь к Dockerfile для сборки образа FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Проброс порта для доступа к FastAPI
    depends_on:
      - redis
      - db
    env_file:
      - .env
      - db/db.env

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:${REDIS_PORT}  # Проброс порта Redis
    volumes:
      - redis_data:/data  # Сохранение данных Redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASS}
    env_file:
      - redis.env

  # PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:${DB_PORT}  # Проброс порта PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных PostgreSQL
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - db/db.env

# Тома для хранения данных
volumes:
  redis_data:
  postgres_data:
