services:
  app:
    image: bitrix-fastapi-image:latest
    container_name: bitrix-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - db/db.env
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
          - mynetwork


  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db/db.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

# Тома для хранения данных
volumes:
#  redis_data:
  postgres_data:
