"""initial

Revision ID: 242ff2bea6b4
Revises: 
Create Date: 2026-02-18 11:24:01.106270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242ff2bea6b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitrix_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_app', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('client_secret', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('form_id', sa.VARCHAR(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('accesses', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms')
    op.drop_table('bitrix_auth')
    # ### end Alembic commands ###
